# Generated by Django 5.2.1 on 2025-05-27 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('store', models.TextField(max_length=100)),
                ('price', models.IntegerField()),
                ('brand', models.CharField(choices=[('J', 'Jordan'), ('C', 'Converse'), ('P', 'Puma'), ('N', 'New Balance')], default='J', max_length=1)),
                ('sneaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.sneaker')),
            ],
        ),
    ]
